import subprocess
import re
from pathlib import Path
import argparse
import csv
import importlib

'''
INSTANTIATE_DEVICE_TYPE_PY_FILE includes the python files which test cases
are generated by instantiate_device_type_tests function. Please check your
test python files also include this function.
'''
INSTANTIATE_DEVICE_TYPE_PY_FILE = [
    "test_torch",
    "test_nn",
    # TO BE ADDED
]

"""
if test cases are more than SPLIT_SIZE in a python file, test cases will
generate splited csv.
"""
SPLIT_SIZE = 100

def write_csv(csv_path, rows):
    with open(csv_path, 'w', newline='') as f:
        csv_writer = csv.writer(f)
        csv_writer.writerow(['test_filename', 'test_case_name'])
        csv_writer.writerows(rows)


def parse_case_name_from_py(test_file_path, csv_path, device="CUDA"):
    is_generated_test = False
    for name in INSTANTIATE_DEVICE_TYPE_PY_FILE:
        if test_file_path[:-3].endswith(name):
            is_generated_test = True
            lib_name = name
    file_name = Path(test_file_path).stem

    # pick up cuda tests to minimize caculation
    if is_generated_test:
        lib = importlib.import_module(lib_name)
        type_lst = {}
        for cls_name in lib.__dict__.keys():
            if cls_name.startswith("Test") and cls_name.endswith(device):
                obj_type = lib.__dict__[cls_name]
                index = 0
                rows = []
                for name in obj_type.__dict__.keys():
                    if name.startswith("test_"):
                        rows.append([file_name, name])
                        if len(rows) % SPLIT_SIZE == 0:
                            csv_path_obj = csv_path[:-4] + "_" + cls_name + "_" + str(index) + ".csv"
                            write_csv(csv_path_obj, rows)
                            print(f"=== {file_name}.py.{cls_name}_{index} : Total case number is {len(rows)} ===")
                            rows = []
                            index += 1

                if len(rows) != 0:
                    csv_path_obj = csv_path[:-4] + "_" + cls_name + "_" + str(index) + ".csv"
                    write_csv(csv_path_obj, rows)
                    print(f"=== {file_name}.py.{cls_name}_{index} : Total case number is {len(rows)} ===")
        return

    ret = subprocess.Popen("cat {} | grep 'def test_'".format(test_file_path), shell=True, stdout=subprocess.PIPE)
    rows = []
    while ret.poll() is None:
        assert ret.wait() == 0, "Popen is broken!"
        lines = ret.stdout.readlines()
        for l in lines:
            pat = re.compile(r"def (.*)[(]", re.S)
            name = re.findall(pat, str(l, 'utf-8'))
            rows.append([file_name, name[0]])

    write_csv(csv_path, rows)
    print(f"=== {file_name}.py : Total case number is {len(rows)} ===")

def parse_case_name_from_csv(csv_file_path, csv_path, speci_failed_test):
    rows = []
    with open(csv_file_path, 'r', newline='') as f:
        csv_reader = csv.reader(f)
        titles = next(csv_reader)
        for row in csv_reader:
            if speci_failed_test:
                if row[2] == "failed":
                    rows.append(row[:2])
            else:
                rows.append(row[:2])
        write_csv(csv_path, rows)
    print(f"=== Total case number is {len(rows)} ===")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Get the test case name of the input file",
        formatter_class=argparse.RawTextHelpFormatter,
    )

    parser.add_argument("test_file_path", type=str, help="The file that need to parser the test case name")

    parser.add_argument("--specified_failure_test", action="store_true", help="Only read failed test case from result report")

    parser.add_argument("--csv_file", type=str, default="", help="The csv file to save the all test case")

    args = parser.parse_args()
    test_file_path = args.test_file_path
    csv_file = args.csv_file

    if test_file_path.endswith(".py"):
        parse_case_name_from_py(test_file_path, csv_file)
    elif test_file_path.endswith(".csv"):
        parse_case_name_from_csv(test_file_path, csv_file, speci_failed_test=args.specified_failure_test)
    else:
        print("Unsupport file format {}, Only suport .py and .csv file".format(test_file_path))
