[pytest]
addopts =
    # show summary of all tests that did not pass
    -rEfX
    # Make tracebacks shorter
    --tb=native
    # capture only Python print and C++ py::print, but not C output (low-level Python errors)
    --capture=sys
    # don't suppress warnings, but don't shove them all to the end either
    -p no:warnings
#    # specify the number of processes when using pytest-xdist for multiprocess testing
#    -n=4
testpaths =
    test
junit_logging_reruns = all
