python bert/run_bert.py --config_file_path bert/configs/daily/cfg_batch_1_seqlength_128_daily.py --mode verify
python bert/run_bert.py --config_file_path bert/configs/daily/cfg_batch_1_seqlength_256_daily.py --mode fast_verify
python bert/run_bert.py --config_file_path bert/configs/daily/cfg_batch_1_seqlength_512_daily.py --mode fast_verify
python bert/run_bert.py --config_file_path bert/configs/daily/cfg_batch_2_seqlength_128_daily.py --mode verify
python bert/run_bert.py --config_file_path bert/configs/daily/cfg_batch_2_seqlength_256_daily.py --mode fast_verify
python bert/run_bert.py --config_file_path bert/configs/daily/cfg_batch_2_seqlength_512_daily.py --mode fast_verify
python bert/run_bert.py --config_file_path bert/configs/daily/cfg_batch_4_seqlength_128_daily.py --mode fast_verify
python bert/run_bert.py --config_file_path bert/configs/daily/cfg_batch_4_seqlength_256_daily.py --mode fast_verify
python bert/run_bert.py --config_file_path bert/configs/daily/cfg_batch_4_seqlength_512_daily.py --mode fast_verify